{
 "title": "Sealed Secrets Controller",
 "description": "Sealed Secrets Controller",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Unseal Request Rate",
   "type": "graph",
   "description": "Rate of unseal requests by action",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sealed_secrets_controller_unseal_attempts_total{pod=~\"$pod\"}[1m])) by (action)",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "Unseal Error Rate",
   "type": "graph",
   "description": "Rate of unseal errors by action",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sealed_secrets_controller_unseal_attempts_total{pod=~\"$pod\", status=\"failure\"}[1m])) by (action)",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "Unseal Request Count",
   "type": "graph",
   "description": "Count of unseal requests by action",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sealed_secrets_controller_unseal_attempts_total{pod=~\"$pod\"}",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "Unseal Error Count",
   "type": "graph",
   "description": "Count of unseal errors by action",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sealed_secrets_controller_unseal_attempts_total{pod=~\"$pod\", status=\"failure\"}",
     "legendFormat": "{{ action }}"
    }
   ]
  }
 ]
}